name: stock_scan_presentation
description: Stock Scan Parser presentation layer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_screenutil: ^5.5.3+2
  go_router: ^4.2.7
  stock_scan_domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
